spring:
  application:
    name: rest
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgrespw
    type: com.zaxxer.hikari.HikariDataSource
  flyway.enabled: false

springdoc:
  paths-to-match: /public/**
  api-docs:
    path: /public/api.json
  swagger-ui:
    path: /public

logging:
  level:
    finance.tegro: DEBUG
