spring:
  application:
    name: api
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgrespw
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

cloud:
  yandex:
    region: ru-central1
  aws:
    sqs:
      endpoint: https://message-queue.api.cloud.yandex.net/
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

lite.client:
  ip: -1182143975
  port: 36573
  key: "ZYe6sDZZc63sH3JnpIS8Yj86NFGnRlQF9NOvzl6UM0c="

logging:
  level:
    finance.tegro: DEBUG
